export const JSON_SCHEMA_DRAFT =
  "https://json-schema.org/draft/2020-12/schema";
export const AGENT_SCHEMA_VERSION = "1.2.0";
export const AGENT_PROTOCOL_VERSION = "digital-key-agent/v1";

function objectSchema(id, title, properties = {}, required = []) {
  return {
    $schema: JSON_SCHEMA_DRAFT,
    $id: `urn:nuedc:digital-key:${id}`,
    title,
    type: "object",
    additionalProperties: false,
    properties,
    ...(required.length > 0 ? { required } : {}),
  };
}

const emptyResultSchema = objectSchema(
  "result.generic",
  "通用命令结果",
  {},
);
emptyResultSchema.additionalProperties = true;

const simulationDefinitions = [
  {
    operation: "simulation.state.get",
    title: "读取仿真状态",
    description: "读取生命周期、钥匙姿态、门锁状态和最近一次测量快照。",
    modes: ["simulation"],
    kind: "query",
    execution: "immediate",
    safety: "read",
    changesState: false,
    requiresIdempotencyKey: false,
    requiresStateRevision: false,
    risk: {
      level: "low",
      tier: "open",
      reason: "只读取内存中的仿真状态",
    },
    argumentsSchema: objectSchema(
      "simulation.state.get.arguments",
      "读取仿真状态参数",
    ),
    resultSchema: emptyResultSchema,
  },
  {
    operation: "lock.snapshot.get",
    title: "读取门锁快照",
    description: "读取当前定位、区域判定、身份校验和锁状态。",
    modes: ["simulation"],
    kind: "query",
    execution: "immediate",
    safety: "read",
    changesState: false,
    requiresIdempotencyKey: false,
    requiresStateRevision: false,
    risk: {
      level: "low",
      tier: "open",
      reason: "只读取门锁计算结果",
    },
    argumentsSchema: objectSchema(
      "lock.snapshot.get.arguments",
      "读取门锁快照参数",
    ),
    resultSchema: emptyResultSchema,
  },
  {
    operation: "simulation.lifecycle.set",
    title: "设置仿真生命周期",
    description: "启动、暂停、停止或重置仿真时钟。",
    modes: ["simulation"],
    kind: "command",
    execution: "immediate",
    safety: "mutating",
    changesState: true,
    requiresIdempotencyKey: true,
    requiresStateRevision: true,
    risk: {
      level: "medium",
      tier: "warned",
      reason: "改变仿真运行状态",
    },
    argumentsSchema: objectSchema(
      "simulation.lifecycle.set.arguments",
      "设置仿真生命周期参数",
      {
        state: {
          type: "string",
          enum: ["running", "paused", "stopped", "reset"],
        },
      },
      ["state"],
    ),
    resultSchema: emptyResultSchema,
  },
  {
    operation: "simulation.key.setPose",
    title: "设置数字钥匙姿态",
    description: "设置钥匙二维位置、地址和激活状态并重新计算门锁。",
    modes: ["simulation"],
    kind: "command",
    execution: "immediate",
    safety: "mutating",
    changesState: true,
    requiresIdempotencyKey: true,
    requiresStateRevision: true,
    risk: {
      level: "medium",
      tier: "warned",
      reason: "改变仿真钥匙位置并触发门锁状态重算",
    },
    argumentsSchema: objectSchema(
      "simulation.key.setPose.arguments",
      "设置数字钥匙姿态参数",
      {
        xMm: { type: "number" },
        yMm: { type: "number" },
        timeMs: { type: "number", minimum: 0 },
        active: { type: "boolean" },
        keyAddress: { type: "integer", minimum: 0, maximum: 65535 },
      },
      ["xMm", "yMm"],
    ),
    resultSchema: emptyResultSchema,
  },
  {
    operation: "simulation.lock.setExpectedId",
    title: "设置门锁期望 ID",
    description: "设置仿真门锁接受的低 4 bit 数字钥匙 ID。",
    modes: ["simulation"],
    kind: "command",
    execution: "immediate",
    safety: "mutating",
    changesState: true,
    requiresIdempotencyKey: true,
    requiresStateRevision: true,
    risk: {
      level: "medium",
      tier: "warned",
      reason: "改变仿真身份校验配置",
    },
    argumentsSchema: objectSchema(
      "simulation.lock.setExpectedId.arguments",
      "设置门锁期望 ID 参数",
      {
        expectedId: { type: "integer", minimum: 0, maximum: 15 },
      },
      ["expectedId"],
    ),
    resultSchema: emptyResultSchema,
  },
  {
    operation: "simulation.faults.set",
    title: "设置仿真故障",
    description: "设置锚点离线、多径偏差、ID 不匹配或数据超时故障。",
    modes: ["simulation"],
    kind: "command",
    execution: "immediate",
    safety: "mutating",
    changesState: true,
    requiresIdempotencyKey: true,
    requiresStateRevision: true,
    risk: {
      level: "medium",
      tier: "warned",
      reason: "改变仿真测量链路和门锁判定输入",
    },
    argumentsSchema: objectSchema(
      "simulation.faults.set.arguments",
      "设置仿真故障参数",
      {
        profile: {
          type: "string",
          enum: ["none", "anchor", "multipath", "id", "timeout"],
        },
      },
      ["profile"],
    ),
    resultSchema: emptyResultSchema,
  },
  {
    operation: "simulation.scenario.run",
    title: "运行仿真场景",
    description: "异步运行固定种子进入场景并保存可查询的操作结果。",
    modes: ["simulation"],
    kind: "command",
    execution: "async",
    safety: "mutating",
    changesState: true,
    requiresIdempotencyKey: true,
    requiresStateRevision: true,
    risk: {
      level: "high",
      tier: "warned",
      reason: "批量推进仿真时间和状态",
    },
    argumentsSchema: objectSchema(
      "simulation.scenario.run.arguments",
      "运行仿真场景参数",
      {
        name: { type: "string", minLength: 1, maxLength: 64 },
        seed: { type: "integer" },
        keyAddress: { type: "integer", minimum: 0, maximum: 65535 },
        expectedId: { type: "integer", minimum: 0, maximum: 15 },
        bearingDeg: { type: "number", minimum: -180, maximum: 180 },
        sampleIntervalMs: { type: "integer", minimum: 1 },
      },
    ),
    resultSchema: emptyResultSchema,
  },
  {
    operation: "diagnostics.run.start",
    title: "启动诊断",
    description: "异步检查仿真状态、三锚点测量和门锁安全条件。",
    modes: ["simulation"],
    kind: "command",
    execution: "async",
    safety: "mutating",
    changesState: false,
    requiresIdempotencyKey: true,
    requiresStateRevision: false,
    risk: {
      level: "medium",
      tier: "warned",
      reason: "启动可能持续一段时间的诊断操作",
    },
    argumentsSchema: objectSchema(
      "diagnostics.run.start.arguments",
      "启动诊断参数",
      {
        scope: {
          type: "string",
          enum: ["all", "localization", "lock", "measurements"],
        },
      },
    ),
    resultSchema: emptyResultSchema,
  },
];

const liveDefinitions = [
  {
    operation: "recorder.status.get",
    title: "读取 UWB Lab 状态",
    description: "只读代理到 127.0.0.1:4173/api/status。",
    modes: ["live"],
    kind: "query",
    execution: "immediate",
    safety: "read",
    changesState: false,
    requiresIdempotencyKey: false,
    requiresStateRevision: false,
    risk: {
      level: "low",
      tier: "open",
      reason: "只读访问现有 UWB Lab 状态",
    },
    argumentsSchema: objectSchema(
      "recorder.status.get.arguments",
      "读取 UWB Lab 状态参数",
    ),
    resultSchema: emptyResultSchema,
  },
  {
    operation: "recorder.position.get",
    title: "读取电脑拟合后的最终位置",
    description:
      "只读代理到 127.0.0.1:4173/api/position；返回电脑根据串口测距和最终标定模型计算出的距离、角度、质量与参与基站。",
    modes: ["live"],
    kind: "query",
    execution: "immediate",
    safety: "read",
    changesState: false,
    requiresIdempotencyKey: false,
    requiresStateRevision: false,
    risk: {
      level: "low",
      tier: "open",
      reason: "只读访问电脑端已经拟合完成的位置结果",
    },
    argumentsSchema: objectSchema(
      "recorder.position.get.arguments",
      "读取最终位置参数",
    ),
    resultSchema: emptyResultSchema,
  },
  {
    operation: "recorder.calibration.get",
    title: "读取最终标定模型状态",
    description:
      "只读代理到 127.0.0.1:4173/api/calibration/final；用于显示模型是否就绪、标定范围与验证误差。",
    modes: ["live"],
    kind: "query",
    execution: "immediate",
    safety: "read",
    changesState: false,
    requiresIdempotencyKey: false,
    requiresStateRevision: false,
    risk: {
      level: "low",
      tier: "open",
      reason: "只读访问电脑端最终标定模型状态",
    },
    argumentsSchema: objectSchema(
      "recorder.calibration.get.arguments",
      "读取最终标定状态参数",
    ),
    resultSchema: emptyResultSchema,
  },
  {
    operation: "recorder.measurements.list",
    title: "读取 UWB 测量",
    description: "只读代理到 127.0.0.1:4173/api/measurements。",
    modes: ["live"],
    kind: "query",
    execution: "immediate",
    safety: "read",
    changesState: false,
    requiresIdempotencyKey: false,
    requiresStateRevision: false,
    risk: {
      level: "low",
      tier: "open",
      reason: "只读访问现有 UWB Lab 测距数据",
    },
    argumentsSchema: objectSchema(
      "recorder.measurements.list.arguments",
      "读取 UWB 测量参数",
      {
        limit: { type: "integer", minimum: 1, maximum: 10000 },
        device: { type: "integer", minimum: 1, maximum: 5 },
        sinceMs: { type: "integer", minimum: 0 },
        sessionId: { type: "string", minLength: 1 },
      },
    ),
    resultSchema: {
      $schema: JSON_SCHEMA_DRAFT,
      $id: "urn:nuedc:digital-key:recorder.measurements.list.result",
      title: "UWB 测量列表",
      type: "array",
      items: {},
    },
  },
  {
    operation: "recorder.sessions.list",
    title: "读取 UWB 会话",
    description: "只读代理到 127.0.0.1:4173/api/sessions。",
    modes: ["live"],
    kind: "query",
    execution: "immediate",
    safety: "read",
    changesState: false,
    requiresIdempotencyKey: false,
    requiresStateRevision: false,
    risk: {
      level: "low",
      tier: "open",
      reason: "只读访问现有 UWB Lab 会话列表",
    },
    argumentsSchema: objectSchema(
      "recorder.sessions.list.arguments",
      "读取 UWB 会话参数",
    ),
    resultSchema: {
      $schema: JSON_SCHEMA_DRAFT,
      $id: "urn:nuedc:digital-key:recorder.sessions.list.result",
      title: "UWB 会话列表",
      type: "array",
      items: {},
    },
  },
  {
    operation: "device.ports.list",
    title: "枚举可用串口",
    description:
      "只读代理到 127.0.0.1:4173/api/ports；4180 不加载 serialport，也不直接访问 COM。",
    modes: ["live"],
    kind: "query",
    execution: "immediate",
    safety: "read",
    changesState: false,
    requiresIdempotencyKey: false,
    requiresStateRevision: false,
    risk: {
      level: "low",
      tier: "open",
      reason: "只读取 4173 枚举出的本机串口列表",
    },
    argumentsSchema: objectSchema(
      "device.ports.list.arguments",
      "枚举可用串口参数",
    ),
    resultSchema: {
      $schema: JSON_SCHEMA_DRAFT,
      $id: "urn:nuedc:digital-key:device.ports.list.result",
      title: "可用串口列表",
      type: "array",
      items: {},
    },
  },
  {
    operation: "device.serial.connect",
    title: "连接采集串口",
    description:
      "通过 4173/api/connect 请求 UWB Recorder 连接串口；4180 仅负责 Agent 契约、revision、dry-run 与幂等控制。",
    modes: ["live"],
    kind: "command",
    execution: "immediate",
    safety: "mutating",
    changesState: true,
    requiresIdempotencyKey: true,
    requiresStateRevision: true,
    risk: {
      level: "medium",
      tier: "warned",
      reason: "改变 4173 持有的唯一串口连接状态",
    },
    argumentsSchema: objectSchema(
      "device.serial.connect.arguments",
      "连接采集串口参数",
      {
        path: { type: "string", minLength: 1, maxLength: 260 },
        baudRate: {
          type: "integer",
          enum: [
            9600, 19200, 38400, 57600, 115200, 230400, 460800, 921600,
            1000000, 2000000,
          ],
        },
      },
      ["path", "baudRate"],
    ),
    resultSchema: emptyResultSchema,
  },
  {
    operation: "device.serial.disconnect",
    title: "断开采集串口",
    description:
      "通过 4173/api/disconnect 请求 UWB Recorder 断开串口；重复断开由 4173 安全读回当前状态。",
    modes: ["live"],
    kind: "command",
    execution: "immediate",
    safety: "mutating",
    changesState: true,
    requiresIdempotencyKey: true,
    requiresStateRevision: true,
    risk: {
      level: "medium",
      tier: "warned",
      reason: "结束 4173 当前持有的串口采集连接",
    },
    argumentsSchema: objectSchema(
      "device.serial.disconnect.arguments",
      "断开采集串口参数",
    ),
    resultSchema: emptyResultSchema,
  },
  {
    operation: "calibration.setup.configure",
    title: "配置固定标定场地",
    description:
      "通过 4173 配置门锁原点与 2～4 个基站的固定三维坐标；4180 不直接访问串口。",
    modes: ["live"],
    kind: "command",
    execution: "immediate",
    safety: "mutating",
    changesState: true,
    requiresIdempotencyKey: true,
    requiresStateRevision: true,
    risk: {
      level: "medium",
      tier: "warned",
      reason: "改变持续标定场地 revision，旧场地点将被隔离",
    },
    argumentsSchema: objectSchema(
      "calibration.setup.configure.arguments",
      "固定标定场地参数",
      {
        name: { type: "string", minLength: 1, maxLength: 80 },
        lock: objectSchema(
          "calibration.setup.lock",
          "门锁原点",
          {
            xMm: { type: "number" },
            yMm: { type: "number" },
            zMm: { type: "number" },
          },
          ["xMm", "yMm", "zMm"],
        ),
        anchors: {
          type: "array",
          minItems: 2,
          maxItems: 4,
          items: objectSchema(
            "calibration.setup.anchor",
            "基站坐标",
            {
              id: { type: "string", minLength: 1, maxLength: 20 },
              xMm: { type: "number" },
              yMm: { type: "number" },
              zMm: { type: "number" },
            },
            ["id", "xMm", "yMm", "zMm"],
          ),
        },
        autoActivate: { type: "boolean" },
      },
      ["lock", "anchors"],
    ),
    resultSchema: emptyResultSchema,
  },
  {
    operation: "calibration.point.capture",
    title: "采集一个地图标定点",
    description:
      "由 4173 使用已连接串口完成稳定等待、15 秒采集、质量检查、候选训练与验证。",
    modes: ["live"],
    kind: "command",
    execution: "async",
    safety: "mutating",
    changesState: true,
    requiresIdempotencyKey: true,
    requiresStateRevision: true,
    risk: {
      level: "medium",
      tier: "warned",
      reason: "新增本地标定数据并训练候选模型，但不会绕过验证强制开锁",
    },
    argumentsSchema: objectSchema(
      "calibration.point.capture.arguments",
      "地图标定点参数",
      {
        setupRevision: { type: "string", minLength: 1, maxLength: 128 },
        xMm: { type: "number" },
        yMm: { type: "number" },
        zMm: { type: "number" },
        durationSeconds: { type: "integer", minimum: 5, maximum: 60 },
        warmupSeconds: { type: "integer", minimum: 0, maximum: 10 },
        minimumSynchronizedGroups: {
          type: "integer",
          minimum: 20,
          maximum: 2000,
        },
      },
      ["setupRevision", "xMm", "yMm"],
    ),
    resultSchema: emptyResultSchema,
  },
  {
    operation: "calibration.candidate.get",
    title: "读取持续标定状态",
    description:
      "读取场地 revision、采集点、正式/候选模型、验证指标与回退历史。",
    modes: ["live"],
    kind: "query",
    execution: "immediate",
    safety: "read",
    changesState: false,
    requiresIdempotencyKey: false,
    requiresStateRevision: false,
    risk: {
      level: "low",
      tier: "open",
      reason: "只读访问 4173 持续标定状态",
    },
    argumentsSchema: objectSchema(
      "calibration.candidate.get.arguments",
      "读取持续标定状态参数",
    ),
    resultSchema: emptyResultSchema,
  },
  {
    operation: "calibration.model.activate",
    title: "激活已验证候选模型",
    description:
      "请求 4173 原子切换已通过安全门槛的候选模型；未通过验证的模型必须拒绝。",
    modes: ["live"],
    kind: "command",
    execution: "immediate",
    safety: "mutating",
    changesState: true,
    requiresIdempotencyKey: true,
    requiresStateRevision: true,
    risk: {
      level: "high",
      tier: "warned",
      reason: "改变电脑端正式定位模型，但不提供强制开锁能力",
    },
    argumentsSchema: objectSchema(
      "calibration.model.activate.arguments",
      "候选模型激活参数",
      {
        setupRevision: { type: "string", minLength: 1, maxLength: 128 },
        candidateVersion: { type: "string", minLength: 1, maxLength: 128 },
      },
      ["setupRevision", "candidateVersion"],
    ),
    resultSchema: emptyResultSchema,
  },
  {
    operation: "calibration.model.rollback",
    title: "回退正式标定模型",
    description:
      "请求 4173 回退到最近历史模型；不会修改串口参数或直接控制门锁。",
    modes: ["live"],
    kind: "command",
    execution: "immediate",
    safety: "mutating",
    changesState: true,
    requiresIdempotencyKey: true,
    requiresStateRevision: true,
    risk: {
      level: "medium",
      tier: "warned",
      reason: "切换电脑端正式定位模型到上一安全版本",
    },
    argumentsSchema: objectSchema(
      "calibration.model.rollback.arguments",
      "模型回退参数",
      {
        setupRevision: { type: "string", minLength: 1, maxLength: 128 },
      },
      ["setupRevision"],
    ),
    resultSchema: emptyResultSchema,
  },
];

export const DIGITAL_KEY_COMMAND_DEFINITIONS = [
  ...simulationDefinitions,
  ...liveDefinitions,
];
